# Generated by Django 3.1.4 on 2021-01-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_auto_20210106_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='certificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='interconsulta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
