# Generated by Django 3.1.4 on 2021-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0004_auto_20210106_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='incapacidad_medica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
